output-dir: molpal_1k
--write-intermediate
--write-final
--retrain-from-scratch

pool: lazy
library: /pool001/mcox340/molpal-maba/molpal_test/tutorial/libraries/liquid_stock_first1k.csv

init-size: 0.05
batch-size: 0.05

objective: docking
objective-config: docking.ini
--minimize

top-k: 10
max-iters: 3
