output-dir: molpal_1k_maba
--write-intermediate
--write-final
--retrain-from-scratch

pool: lazy
library: /pool001/mcox340/molpal-maba/molpal_maba/libraries/liquid_stock_first1k.csv

fingerprint: pair
length: 2048
radius: 2

model: mpn
conf-method: mve

init-size: 0.05
batch-size: 0.05

objective: docking
objective-config: /pool001/mcox340/molpal-maba/molpal_maba/configs/docking.ini
--minimize

top-k: 0.01
max-iters: 5

ncpu: 12
